language: cpp
sudo: required

services:
- docker

os:
- linux

compiler:
- clang
- gcc

#branches:
#  only:
#  - master
#  - develop

env:
# - BUILD_TYPE=Debug
- BUILD_TYPE=Release
- SH="docker exec -t ubuntu-test bash -c"

before_install:
- docker run -d --name ubuntu-test -v $(pwd):/travis -w /travis ubuntu:latest tail -f /dev/null
- docker ps
- chmod +x .travis/*/*.sh

# install:

script:
- .travis/${TRAVIS_OS_NAME}/build.sh
- .travis/${TRAVIS_OS_NAME}/test.sh

addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt-5.10.1-trusty
    packages:
    - qt510base
    - xvfb
