language: cpp

sudo: required

os:   linux
dist: trusty

compiler: 
- clang
- gcc

addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt542-trusty
    packages:
    - qt54base
    - qt54multimedia
    - xvfb

env:
  global:
  - QTDIR=/opt/qt54 PATH=$PATH:$QTDIR/bin

script:
- mkdir build
- cd build
- cmake ..
- make
- xvfb-run tests/tests
