language: cpp
sudo: required

services:
- docker

os:
- linux

compiler:
- clang
- gcc

#branches:
#  only:
#  - master
#  - develop

env:
# - BUILD_TYPE=Debug
- BUILD_TYPE=Release

before_install:
- chmod +x .travis/*/*.sh

install:
- .travis/${TRAVIS_OS_NAME}/install.sh

script:
- .travis/${TRAVIS_OS_NAME}/build.sh
- .travis/${TRAVIS_OS_NAME}/test.sh

addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt-5.10.1-trusty
    packages:
    - qt510base
    - xvfb
