os:   linux
dist: trusty
sudo: required

language: cpp

compiler: 
- clang
- gcc

addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt542-trusty
    packages:
    - qt54tools
    - xvfb

script:
- mkdir build
- cd build
- cmake ..
- make
- xvfb-run tests/tests
